### ISSUE TITLE
search bar does not work on ampersand tarski documentation

### ISSUE THREAD

**Issue by SterredenBreeijen** [AmpersandTarski/documentation#14]
On the ampersand documentation site the search bar is not functioning properly. When trying to look for anything there is no response.

**Comment by hanjoosten** [comment]
Strange. Did you use the right url? As you can see, it works for me:

![IntroductionDocumentationof](https://user-images.githubusercontent.com/1159672/57837179-8c235f80-77c2-11e9-846b-14be6443cb5e.gif)

**Comment by SterredenBreeijen** [comment]
Yes I used the same url. 
I tried in chrome and firefox and there it is working but Irina just tried in edge and there it does not work. I'll tell her to switch the browser. It is not working in IE either.

**Comment by hanjoosten** [comment]
There is nothing much we can do. We use gitbook to create the documentation. We think they do an awsome job normally. I have informed them about the missing support for Edge. Let's hope they can fix that. Until then, as a workaround, use one of the browsers that do work.

**Comment by SterredenBreeijen** [comment]
Ok, thank you!
