### ISSUE TITLE
Documentation on relations

### ISSUE THREAD

**Issue by lorenzo-a** [AmpersandTarski/documentation#15]
Some small suggestions, please correct me if I'm wrong :)

On the following page: [(https://github.com/AmpersandTarski/documentation/blob/master/the-language-ampersand/relations.md)]

In the first table under the Properties chapter:
INJ injective For any b in B there can be not more than one a in A in the population of r. So, every b occurs not more than once in the domain of r.
Should it not be: not more than once in the target of r?

Somewhat related:
Would it not be clearer to use the same terminology consistently? In chapter 'syntax and meaning' the following is written: The left hand concept, Person, is called the source of the relation and the right concept, Building, is called the target. 

Here the term 'source' is used, later on 'domain' is used. 

There are additional relations that can be specified on endo relations. An endo relation is a relation where the source and target concepts are equal. r[A*A].

Shouldn't the first relations be replaced by properties?

**Comment by LloydRutledge** [comment]
Thanks Lorenzo! I corrected this. I also replaced domain with source.
