### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by attaxia** [AmpersandTarski/documentation#16]
In this page:
https://github.com/AmpersandTarski/documentation/blob/master/the-language-ampersand/the-rule-statement.md

The "chapter about rules" is broken.

**Comment by sjcjoosten** [comment]
In this page: https://github.com/ampersandtarski/documentation/ all links to any of the gitbooks (like https://www.gitbook.com/book/ampersandtarski/the-tools-we-use-for-ampersand ) are broken.

Did gitbook go offilne? Tagging @hanjoosten

**Comment by attaxia** [comment]
It did not, the gitbook can be found here:
https://ampersandtarski.gitbook.io/documentation/

**Comment by hanjoosten** [comment]
Typical example of broken links because of updated documentation. Now this should be fine.
