### ISSUE TITLE
Link to the compiled version of Enrollment needs to be added

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/documentation#4]
This link was lost somewhere along the line last year. 
Now there is a text that the executable is not there and this will be fixed later.
page: https://ampersandtarski.gitbook.io/documentation/tutorial-rap3/example-system-enrollment 

If you compile the file and give me the link, I can fix the tutorial page.

**Comment by stefjoosten** [comment]
I will notify you as soon as RAP is up and running with enrollment in it.

**Comment by EstherHageraats** [comment]
It's added. Thanks.
