### ISSUE TITLE
Which RAP3 do students have to use?

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/documentation#5]
On the tutorial page where RAP3 is introduced there are two different links to RAP3:
"This section introduces the tool you will use during the course: [RAP3](http://ampersand.tarski.nl/RAP3). This tool stores Ampersand-scripts in which you can specify, analyze and build information systems. It runs in the cloud, so all you need is a browser and to [click here](http://rap.cs.ou.nl/RAP3) to start using it."

Which one do students have to use?
If you let me know I will update the tutorial.

**Comment by stefjoosten** [comment]
Let us stick to rap.cs.ou.nl/RAP3. After changing it, would you close this issue?

**Comment by EstherHageraats** [comment]
Done
