### ISSUE TITLE
Will the student account still be reset when RAP3 is updated

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/documentation#6]
The tutorial page where RAP3 is introduced has the following line: "When RAP3 is updated, probably your account will be reset. You need to register again." Is this still the case?

A bit further down the warning is even bigger:
"Important note:
RAP3 is being improved constantly, new releases can be done daily.
Currently all account information and scripts will be deleted with each new release.
So: keep a local copy of your scripts and if you cannot login anymore, just re-create your account."
Is that still the case?

And further down: "A note of caution: currently a new release of RAP3 will destroy all that is in the database, also your scripts. So save a copy of you script locally at the end of each working session."
This is probably the same issue as the second one. Is this still the case?

**Comment by stefjoosten** [comment]
No. In the unlikely event that it happens during a course run, we can simply inform the students. I have adapted the text and removed the bigger warnings.
