### ISSUE TITLE
Picture not visible

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/documentation#8]
In het tutorial page documentation/tutorial-rap3/conceptual-model-enrollment.md there is a picture of a conceptual model.
The picture is visible for me when I edit the page, but not when I just read the page. So I guess also for other read-only visitors, the picture is not there.
![schermafdruk 2018-09-04 11 36 58](https://user-images.githubusercontent.com/18698059/45023601-2083d280-b037-11e8-99f7-08c3e8261f50.png)

**Comment by hanjoosten** [comment]
This is strange behaviour. I think this is a bug in gitbook, but I need to investigate.

**Comment by stefjoosten** [comment]
I fixed it.
